[package]
name = "atomic_lock"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.10.0"

[dev-dependencies]
cairo_test = "2.14.0"
snforge_std = "0.53.0"

[[target.starknet-contract]]
sierra = true
